#!/usr/bin/env bash
# Regenerate valkey-internals.md by concatenating chapters 00–08.
# Usage: ./build-combined.sh   (run from the notes/ directory)
set -euo pipefail
cd "$(dirname "$0")"

OUT=valkey-internals.md
CHAPTERS=(
  00-orientation.md
  01-server-lifecycle-and-event-loop.md
  02-command-execution-path.md
  03-clients-and-networking.md
  04-keyspace-and-data-model.md
  05-expiration-and-eviction.md
  06-persistence-rdb-aof.md
  07-replication.md
  08-cluster-bus-and-failover.md
  09-threading-and-io-model.md
)

{
  cat <<'PREAMBLE'
# Valkey Internals — Combined Book

A single-file concatenation of chapters 00–09, for reading straight through or searching
in one place. Each chapter also exists standalone in this directory. Cross-references like
"chapter 03" point to the correspondingly numbered section below. Every `file:line` anchor
was verified against the checkout at authoring time; grep the function name if a line has
drifted.

> Generated by `build-combined.sh` from `00`–`09`. Edit the individual files, then rerun it.

## Contents

- [00 — Orientation](#00--orientation)
- [01 — Server Lifecycle & the Event Loop](#01--server-lifecycle--the-event-loop)
- [02 — Command Execution Path](#02--command-execution-path)
- [03 — Clients & Networking](#03--clients--networking)
- [04 — Keyspace & Data Model](#04--keyspace--data-model)
- [05 — Expiration & Eviction](#05--expiration--eviction)
- [06 — Persistence: RDB & AOF](#06--persistence-rdb--aof)
- [07 — Replication](#07--replication)
- [08 — Cluster Bus & Failover](#08--cluster-bus--failover)
- [09 — Threading & the I/O Model](#09--threading--the-io-model)

---
PREAMBLE

  for ch in "${CHAPTERS[@]}"; do
    echo
    cat "$ch"
    echo
    echo "---"
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines) from ${#CHAPTERS[@]} chapters."
